### ISSUE TITLE
Make it more configurable

### ISSUE THREAD

**Issue by nickmessing** [ndelvalle/v-blur#1]
I'd suggest adding some way to specify duration and easing as "options", maybe you can accept "options" object in `v-blur` something like `v-blur="{durationg: 0.5, easing: 'ease-in-out', blurred: true}"`?

**Comment by ndelvalle** [comment]
Yeah, good idea, I should make all attributes configurable 🙂. Maybe have some defaults declared on setup time, and let the user modify them again when using it like you suggested.

**Comment by ndelvalle** [comment]
I made `opacity`, `filter` and `transition` configurable, I thought there was no need of adding duration and easing having the `transition` property available 🙂.
