### ISSUE TITLE
Option to prevent interaction under the blur zone

### ISSUE THREAD

**Issue by irongomme** [ndelvalle/v-blur#115]
Is there a way to prevent interaction with elements which are under the blur zone ?

**Comment by ndelvalle** [comment]
Nop, that would be a nice option! 🤓

**Comment by rahulnpadalkar** [comment]
@ianaya89 isn't it easy to add `pointer-events:none;` css rule on element the element on which v-blur is used?

**Comment by ndelvalle** [comment]
@rahulnpadalkar I don't think it would be difficult to implement, but I currently do not have the time, but please feel free to contribute 💪🏻

**Comment by emahuni** [comment]
this is not working anymore, if it ever worked.
