### ISSUE TITLE
blurConfig doesn't seem to work.. and conflict with opacity

### ISSUE THREAD

**Issue by vesper8** [ndelvalle/v-blur#5]
I can get this to work just fine if I only use isBlurred

but if I used the blurConfig, I can't seem to activate it

```
<img id="logo" v-blur="blurConfig" />
```

```
      blurConfig: {
        isBlurred: false,
        opacity: 0,
        filter: 'blur(1.2px)',
        transition: 'all .3s linear',
      },
```

Then if I call this.blurConfig.isBlurred = true;

Nothing happens

but if I use

```
<img id="logo" v-blur="isBlurred" />
```

then when I do this.isBlurred = true

Then the blur is activated

Also another problem I noticed is, attaching isBlurred to an element automatically applies an opacity to it.. even if isBlurred is currently set to false. This causes conflicts in my application since I want to attach isBlurred on items which are initially hidden by having their opacity set to 0

Is there a way to attach the v-blur directive dynamically to get around this?

**Comment by ndelvalle** [comment]
@vesper8 can you create a [codesandbox](https://codesandbox.io) so we can solve this faster? Sadly I'm a bit busy these days. But I'll catch up soon.

**Comment by ndelvalle** [comment]
@vesper8 I fix your first issue. The second problem you mentioned, it could be solved by setting the `opacity` value to the one you actually want, now that using the config object works 🙂. You can test it in [codesandbox](https://codesandbox.io/s/823o069zoj)

**Comment by ndelvalle** [comment]
v-blur 1.0.2 published 🎉(Related to this issue)
